### ISSUE TITLE
[firestore-sentiment-analysis] Postinstall magnitude value seems incorrect

### ISSUE THREAD

**Issue by agau4779** [FirebaseExtended/experimental-extensions#12]
## Expected Behavior

Score can be a positive or negative float, between -1 and 1, and magnitude is the absolute value of that. Magnitude is always positive and should not exceed 1. 

## Actual Behavior

The example provided in the [POSTINSTALL](https://github.com/FirebaseExtended/experimental-extensions/blob/next/firestore-sentiment-analysis/POSTINSTALL.md): 
```
{
  to_analyze: 'Firebase is absolutely amazing. 10/10, would recommend it to everyone I know.',
  sentiment: {
    magnitude: 1.899999976158142,
    score: 0.8999999761581421,
  },
}
```

**Comment by jhuleatt** [comment]
FYI @PaulTR

**Comment by PaulTR** [comment]
Weird, that might be a bug on the GCP side of things. Popped that text into their tester at https://cloud.google.com/natural-language and got [1.9 for the entire document as well](https://screenshot.googleplex.com/39NMU5hqkxYS4Nr)

**Comment by PaulTR** [comment]
So thinking about it, that's just the total from every segment that it assigned magnitude to. I think we can either clarify that in the extension's documentation, or maybe average everything that's provided by the API and use that as the magnitude

**Comment by jhuleatt** [comment]
Took a look at the [docs for magnitude](https://cloud.google.com/natural-language/docs/basics#sentiment_analysis) and they say:

> magnitude indicates the overall strength of emotion (both positive and negative) within the given text, **between `0.0` and `+inf`**. Unlike score, magnitude is not normalized; each expression of emotion within the text (both positive and negative) contributes to the text's magnitude (so longer text blocks may have greater magnitudes).

Seems like this is WAI?
