### ISSUE TITLE
[firestore-sentiment-analysis] Reconfiguring sentiment output field name 

### ISSUE THREAD

**Issue by agau4779** [FirebaseExtended/experimental-extensions#14]
## Expected Behavior
Reconfiguring the sentiment output field name to a non-default value, and writing to Firestore should cause the Extension to write the sentiment scores into the newly specified output field name.

## Actual Behavior

The extension writes to both the new field name and the old field name:

![Screenshot 2021-01-14 at 2 13 30 PM](https://user-images.githubusercontent.com/1696790/104655593-c49fce80-5672-11eb-86e4-da7c115c27b4.png)

## Steps to Reproduce the Problem

1. Install firestore-sentiment-analysis
2. Reconfigure the output field name param to something other than `sentiment`
3. Write to the collection a document with key:value `to_analyze`: `some example text`
4. See the output sentiment created twice, once for the default key value and once for the newly specified key.

## Specifications

- Extension name: firestore-sentiment-analysis
- Version: 0.0.1

**Comment by jhuleatt** [comment]
@PaulTR maybe the `snapshot.ref.set` that hardcodes the `sentiment` field is left over from testing? 

https://github.com/FirebaseExtended/experimental-extensions/blob/0c2647c839847d2485fcd69ff6efbd7222fbc237/firestore-sentiment-analysis/functions/index.js#L119

It isn't awaited, and seems like it's reduntant with the transaction below it.

**Comment by PaulTR** [comment]
Oh yeah that seems likely. I'll pull that out and make sure everything still works this week.
