### ISSUE TITLE
[firestore-scheduled-writes] Error logs appear even with successful writes

### ISSUE THREAD

**Issue by dackers86** [FirebaseExtended/experimental-extensions#31]
## Expected Behavior

Logging should be successful and not contain error logs when a successful rite has been made.

## Actual Behavior

An error log appears, stating the document cannot be found. The extensions appear to have worked as expected.

## Steps to Reproduce the Problem
- Follow standard directions for installation in README.
- Run the example code snippet

```js
const TEN_MINUTES_MS = 10 * 60 * 1000;

firebase
  .firestore()
  .collection("queued_writes")
  .add({
    state: "PENDING",
    data: { message: "Hello from the future!" },
    deliverTime: firebase.firestore.Timestamp.fromMillis(
      Date.now() + TEN_MINUTES_MS
    )
  });
```

What happened? How can we make the problem occur?

￼
![image](https://user-images.githubusercontent.com/2060661/105473719-51f7aa00-5c95-11eb-97e8-3f19173c6551.png)

## Specifications

- Extension name: firestore-schedule-writes
- Version: 0.0.1

**Comment by YannicEl** [comment]
Is this being worked on?
If not I could issue a PR.

**Comment by mbleigh** [comment]
PR would be great! I didn't notice this issue until just now

**Comment by YannicEl** [comment]
the PR is ready
