### ISSUE TITLE
[storage-extract-image-text] Invalid link appears on extension details

### ISSUE THREAD

**Issue by dackers86** [FirebaseExtended/experimental-extensions#34]
## Expected Behavior
Extension details link should link to a valid page showing the extensions details.

## Actual Behavior
It directs to an invalid link similar to `https://console.firebase.google.com/project/extensions-testing/extensions/instances/null.`

## Steps to Reproduce the Problem

1. Install the latest `storage-extract-image-text` extension.
2. Select the extensions from your list of extensions.
3. Click `Extension Details` as shown below...

￼
![image](https://user-images.githubusercontent.com/2060661/106731206-223a9180-6607-11eb-9ca8-e406596ca9a7.png)

## Specifications

- Extension name: storage-extract-image-text
- Version: 0.0.1

**Comment by cabljac** [comment]
closing as i believe this is fixed in the GCP repo
