### ISSUE TITLE
Merging Sentiment Analysis extension with firestore-nlp-extension

### ISSUE THREAD

**Issue by elvisun** [FirebaseExtended/experimental-extensions#36]
The [sentiment analysis extension](https://github.com/FirebaseExtended/experimental-extensions/tree/next/firestore-sentiment-analysis) is very similar to the [Firestore NLP extension](https://github.com/FirebaseExtended/firestore-nlp-extension), which is written by an intern on the Firebase ML team last summer. Both extensions uses the Cloud NLP API and are very similar in the way they are built, so I'm proposing that we merge them into one. 

In terms of the delta between the two extensions: 
- The current **Sentiment Analysis Extension** have a small amount of installs.
- The **Firestore NLP Extension** has a richer feature set -  it gives users ability to [choose which of the following tasks to perform](https://github.com/FirebaseExtended/firestore-nlp-extension/blob/master/extension.yaml#L129): sentiment analysis, entity extraction, content classification. Also it might be easier for us to maintain, since it's written in TS and has good unit test coverage.

**Comment by elvisun** [comment]
@jhuleatt Hey Jeff, what's our next step on this?

**Comment by jhuleatt** [comment]
@PaulTR what do you think? Interested in trying to merge these?

**Comment by i14h** [comment]
@dackers86 lets move forward with bringing the nlp extension into this repo and deprecating the sentiment analysis extension
