### ISSUE TITLE
Image Text Extraction function not working, index.js seems to be missing

### ISSUE THREAD

**Issue by SpuriousGer** [FirebaseExtended/experimental-extensions#37]
## Expected Behavior
After installing the experimental extension Image Text Extraction, I would have expected the Cloud Function to be installed properly as well.

## Actual Behavior
Cloud Function is failing because "index.js" is missing.

```
{
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "status": {
      "code": 3,
      "message": "Build failed: lib/index.js does not exist; Error ID: bc73f5cd"
    },
    "authenticationInfo": {
      "principalEmail": "699629296177@cloudservices.gserviceaccount.com"
    },
    "serviceName": "cloudfunctions.googleapis.com",
    "methodName": "google.cloud.functions.v1.CloudFunctionsService.UpdateFunction",
    "resourceName": "projects/MyProjectName/locations/europe-west3/functions/ext-storage-extract-image-text-extractText"
  },
  "insertId": "-6dcq53bdy",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "project_id": "jpabiggmbh-001",
      "region": "europe-west3",
      "function_name": "ext-storage-extract-image-text-extractText"
    }
  },
  "timestamp": "2021-02-16T10:59:36.945647Z",
  "severity": "ERROR",
  "logName": "projects/MyProjectName/logs/cloudaudit.googleapis.com%2Factivity",
  "operation": {
    "id": "operations/anBhYmlnZ21iaC0wMDEvZXVyb3BlLXdlc3QzL2V4dC1zdG9yYWdlLWV4dHJhY3QtaW1hZ2UtdGV4dC1leHRyYWN0VGV4dC9TV0diZURmWHFONA",
    "producer": "cloudfunctions.googleapis.com",
    "last": true
  },
  "receiveTimestamp": "2021-02-16T10:59:37.161659787Z"
}
```

## Steps to Reproduce the Problem
1. Go to the extensions tab in Firebase
2. Choose the experimental extension
3. Choose Image Text Extraction
4. Enter all the details, in my case Europe-West-3 (Frankfurt)

## Specifications

- Extension name: Image Text Extraction
- Version: 0.0.1

**Comment by mogmet** [comment]
I also can't deploy extension.
it looks not commit lib/index.js

other extensions include compiled javascript file
https://github.com/FirebaseExtended/experimental-extensions/blob/next/firestore-sentiment-analysis/functions/index.js
https://github.com/FirebaseExtended/experimental-extensions/blob/next/firestore-auth-claims/functions/lib/index.js
https://github.com/FirebaseExtended/experimental-extensions/blob/next/firestore-schedule-writes/functions/lib/index.js
https://github.com/FirebaseExtended/experimental-extensions/blob/next/firestore-shorten-urls-dynamic-links/functions/lib/index.js

can you commit lib/index.js?
@pavelgj @jhuleatt
