### ISSUE TITLE
[Firestore Bundle Server] Install link points to wrong extension source

### ISSUE THREAD

**Issue by elvisun** [FirebaseExtended/experimental-extensions#47]
## Expected Behavior
Install Firestore Bundle Server

## Actual Behavior
It's pointing to Custom Auth Claim
https://github.com/FirebaseExtended/experimental-extensions/tree/next/firestore-bundle-server

**Comment by dackers86** [comment]
Hi @elvisun 

Can you confirm if you still have an issue here? Or perhaps more information on the problem you are experiencing?

**Comment by elvisun** [comment]
Thanks Darren, the issue seems to have resolved
