### ISSUE TITLE
[firestore-shorten-urls-dynamic-links] Links won't open in Safari (iOS)

### ISSUE THREAD

**Issue by edukun** [FirebaseExtended/experimental-extensions#51]
## Expected Behavior
Short links should open and redirect to full URL in Safari (iOS) like in any Chrome

## Actual Behavior
White screen appears. Clicking anywhere starts redirection

## Steps to Reproduce the Problem
Create a web project (no apps). Configure extension firestore-shorten-urls-dynamic-links or just use REST API to create short links.

I already tried creating an iOS app in console, using efr=1 param, generating the short link manually skipping the app preview, using enableForcedRedirect...

If you open the short url in Chrome, you get a 200 response and then the browser calls same URL with ?_imcp=1 param, and it resolves as a 302 with location the full url.

![chrome](https://user-images.githubusercontent.com/1574284/119647845-0c084980-be21-11eb-9bec-9217cf3cc93f.png)

If you open the short url in Safari, you get a 200 OK response and a white page, that's it. If you open short url with ?_imcp=1 param, you get a 200 instead of 302.

![safari](https://user-images.githubusercontent.com/1574284/119647864-1296c100-be21-11eb-8815-9cbd4b256c95.png)

**Comment by i14h** [comment]
@dackers86 can we look into this? (also apologies for the huge delay in responding)

**Comment by yamankatby** [comment]
Hi @edukun,
Thank you for reporting this issue. I have tried to replicate it however it seems to be working fine.

Steps I made:
- Install an instance of `firestore-shorten-urls-dynamic-links` on firebase project
- Write a document containing a URL field (with params)
- Open the shortURL (I have tried to run it on chrome, firefox, safari, and safari iOS) all work fine.

Please tell me if this is still an issue and if yes please provide more information about how to replicate it.

**Comment by imagineapps1** [comment]
Hi @yamankatby,

I have tested now, and it's working. But I don't know when it got fixed, since it was one year ago. 

I ended up creating a Cloud Function to force the redirection, I'll keep it that way just in case.

**Comment by edukun** [comment]
Hi @yamankatby,

I have tested now, and it's working. But I don't know when it got fixed, since it was one year ago.

I ended up creating a Cloud Function to force the redirection, I'll keep it that way just in case.

**Comment by dackers86** [comment]
Thanks @yamankatby @edukun.

Closing the issue for now.
