### ISSUE TITLE
Question about Transcode Videos on Google Cloud Storage

### ISSUE THREAD

**Issue by rlee1990** [FirebaseExtended/experimental-extensions#57]
How are we able to play the videos after they are transcoded. I do not see a master.meu8 file I saw a manifest.m3u8 file but it is not playable.

**Comment by rlee1990** [comment]
@mbleigh @i14h does anyone know how I can fix this?

**Comment by i14h** [comment]
@rlee1990 thanks for reporting this. I'll close this one and we'll continue on the other issue you created in https://github.com/GoogleCloudPlatform/firebase-extensions/issues/6
