### ISSUE TITLE
Can we use this extension to check if a video has inappropriate content like nudity or violence

### ISSUE THREAD

**Issue by aytunch** [FirebaseExtended/experimental-extensions#61]
I want to do this on the device not on the cloud.
Our users record and chooses videos from their camera or internal storage.
I want to process these videos and check if they are safe before uploading them to Firebase storage.
By using `ffmpeg` I can convert the video in to many images so I can feed them to this plugin.
Do I need a seperate model for the inappropriate filtering?

Could you please direct me to the right path?

EDIT: I have seen a product called `SafeSearch` in Google Cloud Vision
https://cloud.google.com/blog/products/ai-machine-learning/filtering-inappropriate-content-with-the-cloud-vision-api
Does this help with Flutter and doing it in the client?
It gives results very suitable for my case: 

```
"safeSearchAnnotation" : {
      "spoof" : "VERY_UNLIKELY",
      "medical" : "UNLIKELY",
      "adult" : "VERY_UNLIKELY",
      "violence" : "VERY_UNLIKELY"
   }
```

**Comment by dackers86** [comment]
Hi @aytunch.

We have currently have a new `experimental` extension for this scenario. Please see https://github.com/GoogleCloudPlatform/firebase-extensions/tree/main/storage-label-videos


*Alternative resources*

Although I have never used this package, there is a Flutter package https://pub.dev/documentation/firebase_ml_vision/latest/

Additionally there is also a REST endpoint if this could suit your current use case https://cloud.google.com/vision/docs/reference/rest.
