### ISSUE TITLE
Question: How can I sign up to Firebase Extensions Alpha Program?

### ISSUE THREAD

**Issue by inglesuniversal** [FirebaseExtended/experimental-extensions#69]
Hello,

I'm watching Firebase Summit 2021 video and I hear that joining this program would allow me to learn how to build custom cloud functions from the ground up.

I've been a GCP customer for about 3 years so I would love to learn more on this amazing topic.

Regards

**Comment by Ehesp** [comment]
Hey @inglesuniversal you can sign up for the Firebase Alpha program here: https://services.google.com/fb/forms/firebasealphaprogram

**Comment by inglesuniversal** [comment]
Thanks I just applied for it.
