### ISSUE TITLE
Installation Audit

### ISSUE THREAD

**Issue by dackers86** [FirebaseExtended/experimental-extensions#70]
| Ext name    | Valid Source Files | Prs
| ----------- | ----------- | ----------- | 
| firestore-auth-claims      | ✓  || 
| firestore-bundle-server    | ✓   | https://github.com/FirebaseExtended/experimental-extensions/pull/63 | 
|firestore-perspective-toxicity   | n/a  || 
| firestore-scheduld-writes     | ✓ || 
| firestore-sentiment-analysis     | ✓  || 
| firestore-shorten-urls-dynamic-links      | ✓  || 
| storage-extract-image-text      | ✓   || 
| storage-image-labeling   | ✓    || 
| storage-label-videos     | n/a   || 
| storage-mirror-firestore     | ✓  || 
| storage-transcode-videos     | n/a   |

**Comment by i14h** [comment]
@dackers86 is this list needed or should we just close this issue?

**Comment by dackers86** [comment]
This has been completed. Happy to close.
