### ISSUE TITLE
Firestore Bundle Server installations shows ${param:STORAGE_BUCKET}

### ISSUE THREAD

**Issue by dackers86** [FirebaseExtended/experimental-extensions#73]
## Expected Behavior
On installation the extension should pre-fill the current projects default storage bucket,

## Actual Behavior

<img width="731" alt="image" src="https://user-images.githubusercontent.com/2060661/157833183-087c9f11-8a3e-462d-a9cc-a096c56a2054.png">

## Steps to Reproduce the Problem
1. Go to https://github.com/FirebaseExtended/experimental-extensions/tree/next/firestore-bundle-server
2. Select Install on Firebase 

## Specifications

- Extension name: Firestore Bundle Server
- Version: Latest

**Comment by i14h** [comment]
@dackers86 is this fixed?

**Comment by yamankatby** [comment]
> @dackers86 is this fixed?

no, it still exists.

![Screen Shot 2022-04-22 at 11 09 02](https://user-images.githubusercontent.com/35961879/164646458-b120dcbd-a55c-4161-a62f-bc86059dabac.png)

**Comment by yamankatby** [comment]
FYI, Installing from CLI doesn't seem to be an issue

![Screen Shot 2022-04-22 at 11 32 39](https://user-images.githubusercontent.com/35961879/164650486-6e650792-568d-42bb-965a-a4d484ddbeed.png)
