### ISSUE TITLE
Question: is there a plan or a roadmap for 3rd parties being able to build extensions? 

### ISSUE THREAD

**Issue by considine** [FirebaseExtended/experimental-extensions#74]
I see that some 3rd party companies have extensions- Algolia and Mailchimp for example. Since i didn't see any docs on building extensions, I assume that this capability isn't public. Is there a way to apply to build an extension? Will this ever become public?

**Comment by i14h** [comment]
@considine Sorry I missed this issue. Yes there is and it's one of our top priorities. Actually you can sign up as publisher under our EAP agreement. Shoot me an email (imanrahmati@google.com) and I'll guide you how to sign up.
