### ISSUE TITLE
[firestore-bundle-server] Deployment failed

### ISSUE THREAD

**Issue by ciriousjoker** [FirebaseExtended/experimental-extensions#86]
## Expected Behavior

Installing via the Firebase console or CLI should deploy correctly.
The last deployment of the extension in GCP should not say "Version 1, deployment failed at ..."

## Actual Behavior

Installing via CLI or UI fails. The extension installs correctly, but when I check the GCP deployment it says "failed".

The actual error message is:

> Deployment failure:
> Build failed: lib/index.js does not exist; Error ID: bc73f5cd

When I download the .zip with the source code, there is no lib folder, there's just `src/` and `test/` (same as in this Github repo).

## Steps to Reproduce the Problem

Install the extension.

## Specifications

- Extension name: firestore-bundle-server
- Version: v0.1.1

**Comment by i14h** [comment]
@dackers86 can you take a look at this? Jeff can deploy the fixed version

**Comment by ciriousjoker** [comment]
We're also using the experimental [firestore-auth-claims](https://github.com/FirebaseExtended/experimental-extensions/tree/next/firestore-auth-claims), which works perfectly. There's also a lib folder, so I assume someone just forgot to run `tsc` and commit the lib folder here as well?

**Comment by dackers86** [comment]
Yes, that is correct - so `npm` now allows a pre-install script called `prepare`, this means we no longer to commit the generated `lib` files as they are generated in the docker build.

Interestingly, the build logs generate the files - local installation works fine for too installing and deploying the source code locally.

**Comment by huangjeff5** [comment]
I published a new version today after pre-generating the lib files. Please give version 0.1.2 a shot.

**Comment by ciriousjoker** [comment]
Works great, thanks!
