### ISSUE TITLE
 Collaboration

### ISSUE THREAD

**Issue by EASTinphectiON** [FirebaseExtended/experimental-extensions#96]
Anyone intersted on building extensions, plug ins, games and apps let me know. 

ebodeux16@gmail.com

Or hmu on GitHub as I need these ideas turned into a reality for everyone. I will pay and and have registered a company on the behalf of myself and whomever replies to this ad

I look forward to engineering some breakthrough technology and forever becing greatful for learning the process as I am a cplete noob lol.

But I will say I have some good ideas that will need to be immediately consoder by some top notch players.

We need avatar specialists such as bitmoji 

We need drafters for objects 

We need expert script readers and writers in any form for I can explain the idea and I would love one to create it

Would be cool to know someone in these fields as well meet someone who can develop something new yet refresh something old or In yes.

Like copy paste and change / add

Who's in?

**Comment by cabljac** [comment]
closing this
